services:
  mysql:
    image: mysql:8.0
    container_name: mysql_docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_2024
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: labartola_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      # ELIMINÉ ESTA LÍNEA QUE ROMPÍA TODO:
      # - ./writable:/var/www/html/writable   ← ¡ESTA ERA LA QUE MATABA LAS MIGRACIONES!
    environment:
      - CI_ENVIRONMENT=development
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - labartola_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root_password_2024
    ports:
      - "8088:80"
    depends_on:
      - mysql

volumes:
  db_data:

networks:
  labartola_network:
    driver: bridge
